### ISSUE TITLE
Backend > Refactor > Consertar erro ao adicionar usuários.

### ISSUE THREAD

**Issue by ManoMax** [codexjr-dev/dashboard-codex-api#3]
# OVERVIEW 
- Após adicionar um novo usuário com o TAG "gerente", o sistema não cadastrava e printava o seguinte erro:
```json
{
"error": "User validation failed: role: gerente is not a valid enum value for path role."
}
```

# TASK
- [ ] Verificar resposta esperada pelo frontend;
- [ ] Verificar retorno da requisição;
- [ ] Corrigir os dados que estão faltando ou incompatíveis;

**Comment by ManoMax** [comment]
# COMMENTS

- O erro foi identificado no sistema em ambiente local;
- Após realizar o Pull da mais recente versão da API e criar um deploy em ambiente remoto, os problemas pareceram estar corrigidos.
