### ISSUE TITLE
Backend > Docs > Gerar uma Documentação API das rotas (Postman)

### ISSUE THREAD

**Issue by ManoMax** [codexjr-dev/dashboard-codex-api#65]
# OVERVIEW 
- Na ideia de aprimorar a apresentação de nosso projeto, é interessante que uma boa documentação seja escrita.
- Desse modo, a partir do conteúdo já descrito no README.md, agora precisamos complementar informações sobre o sistema, informando quais as rotas existentes da API e suas descrições, bem como o conteúdo exigido no Body, Params e Header dessas requisições, além das respostas e erros esperados.
- Para isso, devemos criar um arquivo chamado `ENDPOINTS.md` na raiz do projeto, contendo esses conteúdos;
- E, além de contextualizar via arquivo.md, para dar mais opções de visualização dessas rotas, uma outra maneira de apresentar a Documentação API é através do Posman;
- Com isso, crie uma Documentação gerada a partir do Postman e adicione o link desse conteúdo ao arquivo ENDPOINTS.md.

# TASK
- [ ] Mapear todas as rotas da API, pelo Postman;
- [ ] Indicar exigências de body, header e params das rotas;
- [ ] Gerar uma documentação a partir do Postman;
- [ ] Utilizar o arquivo `ENDPOINTS.md` da raiz do projeto, para adicionar o link de referencia dessa Documentação gerada;

# LINKS
- Link of Issue README.md: https://github.com/codexjr-dev/dashboard-codex-api/issues/59
- Link of Issue README.md in project: https://github.com/orgs/codexjr-dev/projects/34/views/1?pane=issue&itemId=38095299 
- Link of Issue ENDPOINTS.md: https://github.com/codexjr-dev/dashboard-codex-api/issues/61
- Link of Issue ENDPOINTS.md in projetct: https://github.com/orgs/codexjr-dev/projects/34/views/1?pane=issue&itemId=38913592

**Comment by PedroFDiniz** [comment]
Quebrei esta issue em várias menores, e atualizei os requisitos!
